name: Build and Push Docker Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
  
      image_name:
        description: 'Docker Image Name'
        required: true
        default: 'tictactoe'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/tictactoe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version

      - name: Run Trivy Scan on Image
        run: |
          trivy image --format table --exit-code 0 --output trivy-image-scan.txt ${{ env.IMAGE_NAME }}:latest
          trivy image --format json --output scan_results.json ${{ env.IMAGE_NAME }}:latest

      - name: Upload Trivy Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-security-report
          path: trivy-image-scan.txt
